<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE bookstore[
	 <!ELEMENT bookstore (book+)>   
	 <!ELEMENT book (title+,author+,year+,price+)>   
	 <!ELEMENT title (#PCDATA)>   
	 <!ELEMENT author (#PCDATA)>   
	 <!ELEMENT year (#PCDATA)>   
	 <!ELEMENT price (#PCDATA)>   

]>
<bookstore>
	<book>
		<title>水浒传</title>
		<author>施耐庵</author>
		<year>1341</year>
		<price>10个铜板</price>
	</book>
	<book>
		<title>三国演义</title>
		<author>罗贯中</author>
		<year>1341</year>
		<price>10个铜板</price>
	</book>
	<book>
		<title>三国演义</title>
		<author>罗贯中</author>
		<year>1341</year>
		<price>10个铜板</price>
	</book>
	<book>
		<title>红楼梦</title>
		<author>曹雪芹</author>
		<year>1341</year>
		<price>10个铜板</price>
	</book>
</bookstore>